version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
       # Creates a volume which maps the app/ directory
      # in our project to /app in the container which allows us to sync our code changes to the container running our dev server.
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=mikesecretkey
      # This is to reduce the risk of accidentally enabling debug mode in production which can be a security risk.
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      # This specifies that the db service should be started before this service, 
      # so that the database server is available when the Django application starts.
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme